copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.EntityFramework.Packager\SimpleEventSourcing.EntityFramework.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Newtonsoft.Packager\SimpleEventSourcing.Newtonsoft.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Newtonsoft-PCL.Packager\SimpleEventSourcing.Newtonsoft-PCL.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.NHibernate.Packager\SimpleEventSourcing.NHibernate.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.SQLite.Packager\SimpleEventSourcing.SQLite.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y
copy SimpleEventSourcing.Packager\SimpleEventSourcing.1.0.0-pre2.nupkg ..\..\Nugets /Y